<?php

namespace AppBundle\Repository;

/**
 * AreassocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreassocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
