<?php

namespace AppBundle\Repository;

/**
 * CapitulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapitulosRepository extends \Doctrine\ORM\EntityRepository
{
}
