<?php

namespace AppBundle\Repository;

/**
 * CategoriasproyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriasproyectosRepository extends \Doctrine\ORM\EntityRepository
{
}
