<?php

namespace AppBundle\Repository;

/**
 * ConfiguracionesgeneralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracionesgeneralesRepository extends \Doctrine\ORM\EntityRepository
{
    public function tipoMoneda()
    {

        $em = $this->getEntityManager();

        $dql = 'SELECT c.moneda FROM AppBundle:Configuracionesgenerales c';

        $query = $em->createQuery($dql);

        /** @noinspection OneTimeUseVariablesInspection */
        $tipoMoneda = $query->getResult();


        return $tipoMoneda[0]['moneda'];

    }

    public function configuracionFicheros()
    {

        $em = $this->getEntityManager();

        $dql = 'SELECT c.caminorepositoriodocumento,c.caracteresmascaradocumento,c.extensiondocumento 
                FROM AppBundle:Configuracionesgenerales c';

        $query = $em->createQuery($dql);

        /** @noinspection OneTimeUseVariablesInspection */
        $configuracion = $query->getResult();


        return $configuracion[0];

    }

    public function getDireccionAdjuntos()
    {
        $carpeta  = strtolower($this->configuracionFicheros()['caminorepositoriodocumento']);
        $direccion = 'http://'.$_SERVER['HTTP_HOST'] . ':' . $_SERVER['SERVER_PORT'] . '/contfin/web/' . $carpeta . '/';
        return $direccion;
    }


}
