<?php

namespace AppBundle\Repository;

/**
 * EstadosexpedientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosexpedientesRepository extends \Doctrine\ORM\EntityRepository
{
}
