<?php

namespace AppBundle\Repository;

/**
 * EstadosexpedientesinstanciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadosexpedientesinstanciasRepository extends \Doctrine\ORM\EntityRepository
{
}
