<?php

namespace AppBundle\Repository;

/**
 * EvidenciasexpedientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvidenciasexpedientesRepository extends \Doctrine\ORM\EntityRepository
{
}
