<?php

namespace AppBundle\Repository;

/**
 * GruposasociativosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruposasociativosRepository extends \Doctrine\ORM\EntityRepository
{
}
