<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Historicosestadosexpedientes;
use AppBundle\Entity\Historicosestadosexpedientesobservaciones;

/**
 * HistoricosestadosexpedientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricosestadosexpedientesRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarHistoricoEstadoExpediente($expediente ,$estadoExpedienteInstancia , $user)
    {
        try{

            $em = $this->getEntityManager();
            $historicoEstadoExpediente = new Historicosestadosexpedientes();
            $historicoEstadoExpediente->setExpediente($expediente);
            $historicoEstadoExpediente->setUsuario($user);
            $historicoEstadoExpediente->setFecha(new \DateTime('now'));
            $historicoEstadoExpediente->setEstado($estadoExpedienteInstancia);

            $em->persist($historicoEstadoExpediente);
            $em->flush();

            $msg = 'ok';

        }catch (\Exception $e){

            $msg = 'Se produjo un error al insertar el histórico del expediente';
        }
        return $msg;
    }
}
