<?php

namespace AppBundle\Repository;

/**
 * InstanciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstanciasRepository extends \Doctrine\ORM\EntityRepository
{
}
