<?php

namespace AppBundle\Repository;

/**
 * MinisteriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinisteriosRepository extends \Doctrine\ORM\EntityRepository
{
}
