<?php

namespace AppBundle\Repository;

/**
 * ParametrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrosRepository extends \Doctrine\ORM\EntityRepository
{
}
