<?php

namespace AppBundle\Repository;

/**
 * ParametrosinstanciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametrosinstanciasRepository extends \Doctrine\ORM\EntityRepository
{
}
