<?php

namespace AppBundle\Repository;

/**
 * PersonasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonasRepository extends \Doctrine\ORM\EntityRepository
{
}
