<?php

namespace AppBundle\Repository;

/**
 * PresupuestosproyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestosproyectosRepository extends \Doctrine\ORM\EntityRepository
{
}
