<?php

namespace AppBundle\Repository;

/**
 * PresupuestosgeneralesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestosgeneralesRepository extends \Doctrine\ORM\EntityRepository
{
}
