<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Presupuestosserviciosexpedientesproyectos;

/**
 * PresupuestosserviciosexpedientesproyectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestosserviciosexpedientesproyectosRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarPresupuestoServicioExpedienteProyecto($expediente , $partida)
    {
        try{
            $em = $this->getEntityManager();
            $actual = new \DateTime();
            $year = $actual->format('Y');
            $proyectos = $partida['proyectos'];
            $servicio = $em->getRepository('AppBundle:Servicios')->find($partida['servicio']);
            $numeroEconomico = $em->getRepository('AppBundle:Numeroseconomicos')->find($partida['numeroEconomico']);
            $presupuesServicio = $em->getRepository('AppBundle:Presupuestosservicios')->findOneBy(array('servicio' => $servicio , 'numeroeconomico' => $numeroEconomico , 'anno' => $year));
            $presupuesServicioExp = $em->getRepository('AppBundle:Presupuestosserviciosexpedientes')->findOneBy(array('expediente' => $expediente , 'presupuestoservicio' => $presupuesServicio));
            foreach ($proyectos as $proyecto)
            {
                if($proyecto != '')
                {
                    $presupuesServicioProyectoExp =  new Presupuestosserviciosexpedientesproyectos();
                    $presupuesServicioProyectoExp->setImportesolicitado($proyecto['monto']);
                    $presupuesServicioProyectoExp->setPresupuestoservicioexpediente($presupuesServicioExp);

                    $presupuestoProyecto = $em->getRepository('AppBundle:Presupuestosproyectos')->find($proyecto['proyecto']);
                    $presupuesServicioProyectoExp->setPresupuestoproyecto($presupuestoProyecto);

                    $em->persist($presupuesServicioProyectoExp);
                }
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e){

            $msg = 'Se produjo un error al insertar los proyectos ';
        }
        return $msg;
    }

}
