<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Registrosexpedientes;

/**
 * RegistrosexpedientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrosexpedientesRepository extends \Doctrine\ORM\EntityRepository
{
    public function agregarRegistro($expediente , $registros)
    {
        try{
            $em = $this->getEntityManager();
            foreach ($registros as $registro)
            {
                $registroExpediente = new Registrosexpedientes();
                $registroExpediente->setFecharegistro(new \DateTime($registro['fecha']));
                $registroExpediente->setNumeroregistro($registro['numeroRegistro']);
                $registroExpediente->setDepartamento($registro['departamento']);
                $registroExpediente->setExpediente($expediente);

                $ministerio = $em->getRepository('AppBundle:Ministerios')->find($registro['ministerio']);
                $registroExpediente->setMinisterio($ministerio);

                $em->persist($registroExpediente);
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e){

            $msg = 'Se produjo un error al insertar los registros del expediente';
        }
        return $msg;
    }

    public function modificarRegistro($expediente , $registros)
    {
        try{
            $em = $this->getEntityManager();
            $registrosExpediente = $expediente->getRegistros();

            foreach ($registrosExpediente as $reg)
            {
                $em->remove($reg);
            }
            $em->flush();

            foreach ($registros as $registro)
            {
                $registroExpediente = new Registrosexpedientes();
                $registroExpediente->setFecharegistro(new \DateTime($registro['fecha']));
                $registroExpediente->setNumeroregistro($registro['numeroRegistro']);
                $registroExpediente->setDepartamento($registro['departamento']);
                $registroExpediente->setExpediente($expediente);

                $ministerio = $em->getRepository('AppBundle:Ministerios')->find($registro['ministerio']);
                $registroExpediente->setMinisterio($ministerio);

                $em->persist($registroExpediente);
            }
            $em->flush();
            $msg = 'ok';

        }catch (\Exception $e){

            $msg = 'Se produjo un error al modificar los registros del expediente';
        }
        return $msg;
    }

    public function registrosCartas($expediente)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT r FROM AppBundle:Registrosexpedientes r JOIN r.expediente e
                WHERE e.id = :p1 ORDER BY r.id';
        $query = $em->createQuery($dql);
        $query->setParameter('p1' , $expediente->getId());
        $registros = $query->getResult();
        return $registros;
    }
}