<?php

namespace AppBundle\Repository;


/**
 * SeccionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeccionesRepository extends \Doctrine\ORM\EntityRepository
{
    public function ponerSeccionConfidencial($idSeccion , $confidencial)
    {
        try{
            $em = $this->getEntityManager();
            $seccion = $em->getRepository('AppBundle:Secciones')->find($idSeccion);
            $confidencial == '0' ? $seccion->setConfidencial(false) : $seccion->setConfidencial(true);
            $em->persist($seccion);
            $em->flush();
            $msg = $seccion;

        }catch (\Exception $e){

            $msg = 'Se produjo un error al poner la sección como confidencial';
        }
        return $msg;
    }

    public function listarSecciones()
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT s FROM AppBundle:Secciones s ORDER BY s.id';
        $query = $em->createQuery($dql);
        $total = $query->getResult();
        return $total;
    }
}
