<?php

namespace AppBundle\Repository;

/**
 * ServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarServiciosAddExpediente()
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT s FROM AppBundle:Servicios s 
                WHERE  EXISTS (SELECT p FROM AppBundle:Presupuestosservicios p WHERE p.presupuestounitario - p.valordisponible > 0 AND p MEMBER OF s.presupuestos )';
        $query = $em->createQuery($dql);
        $servicios = $query->getResult();
        return $servicios;
    }
    public function listarServiciosSeccion($idSeccion)
    {
        $em = $this->getEntityManager();
        $dql = 'SELECT serv FROM AppBundle:Servicios serv JOIN serv.seccion s
                WHERE s.id = :p3 ORDER BY serv.id';
        $query = $em->createQuery($dql);
        $query->setParameter('p3' , $idSeccion);
        $total = $query->getResult();
        return $total;
    }
}
